# Generated by Django 5.0.2 on 2024-02-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('ingredients', models.CharField(max_length=1000, verbose_name='Ингридиенты')),
            ],
        ),
    ]
